### PR TITLE
Add support for jspm install out of the box

### PR DESCRIPTION
**Pull request by lookfirst**
(thanks for the UMD support too)

### CODE REVIEW

**Comment by omichelsen** [comment]
Thanks for the PR, but as far as I read the jspm docs, all these things should already work with the current package.json without making specific changes for jspm?

**Comment by lookfirst** [comment]
Nope. Try it yourself.

**Comment by omichelsen** [comment]
Tried it, this work fine: `jspm install npm:angular-clipboard`.

**Comment by lookfirst** [comment]
I doesn't add a dependency on angular.

**Comment by omichelsen** [comment]
No this is on purpose, read up on [peerDependencies](http://jspm.io/0.17-beta-guide/peer-dependencies.html).

**Comment by lookfirst** [comment]
I don't install packages via npm, I like to install them via github because this way it allows me to easily deal with cross repository dependencies as well as easily fork a project.

```
warn github:omichelsen/angular-clipboard@1.4.1 dependency installs skipped as it's a GitHub package with no registry property set.
     If the dependencies aren't needed ignore this message. Alternatively set a registry or dependencies override or use the npm registry version at jspm install npm:angular-clipboard@^1.4.1 instead.
```

So, I have to use an override. Not a huge deal, but kind of a bummer.

**Pull request closed without merging**
